# Generated by Django 4.0.2 on 2022-02-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок сотрудника для списка')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('staff_name', models.CharField(max_length=25, verbose_name='Должность')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('staff_exp', models.IntegerField(verbose_name='Стаж')),
                ('wages', models.IntegerField(verbose_name='ЗП')),
                ('education', models.CharField(max_length=25, verbose_name='Образование')),
                ('duties', models.TextField(verbose_name='Обязанности')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
